### ISSUE TITLE
Enh: Add scroll down when running selection 

### ISSUE THREAD

**Issue by alejohz** [kylebarron/vscode-jupyter-python#3] opened 2022-12-06 15:20 UTC
Hey, first of all thank you for developing this great extension.

It would be really nice to have an automatic scroll down when pressing shift + enter. 

As you can see, code still runs below the editor's current visual frame. 
![vs code ext](https://user-images.githubusercontent.com/109233596/205951483-bc3cfd2b-9638-4d24-8a8b-ed076b1dc5fd.gif)

**Comment by kylebarron** [comment] 2022-12-06 16:05
this might be a duplicate of #2?

**Comment by kylebarron** [comment] 2022-12-06 16:06
I can't really tell what the issue is from your screenshot

**Comment by alejohz** [comment] 2022-12-07 01:17
Thank you for addressing this so quickly. Sorry the gif has so bad resolution, but it is due to github upload restrictions. The "issue" but it is actually an enhancement, is because when you are shift entering content that is lower than your visual frame, it keeps executing but the window stays static. The gif exemplifies that when shift + entering from line 0 to 40, all is well, but after line 40, code keeps executing and cursor keeps going down when shift + entering, but the window does not scroll down thus you don't know what you are executing anymore and have to dropdown manually. 

As i stated originally and in the title, this is an enhancement and QoL improvement.

**Closed as completed** 2022-12-07 17:59 UTC
